import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type RequestStatus = 'soumise' | 'en_cours' | 'pieces_complementaires' | 'validee' | 'prete' | 'livree' | 'rejetee'

// ─── New interface for uploaded files ───────────────────────────────────────
export interface UploadedDocument {
  id: string
  name: string          // Original filename
  type: string          // MIME type (e.g., 'application/pdf', 'image/png')
  size: number          // File size in bytes
  data: string          // Base64 encoded file data
  uploadedAt: string    // ISO date
  requiredDocName: string // Which required document this fulfills
  verified: boolean     // Whether agent has verified this document
}

// ─── New interface for generated official documents ─────────────────────────
export interface GeneratedDocument {
  id: string
  title: string
  htmlContent: string   // Full HTML content for the official document
  generatedAt: string
  generatedBy: string   // Agent name
  fileName: string      // Download filename
}

export interface SatisfactionRating {
  rating: 1 | 2 | 3 | 4 | 5
  comment: string
  ratedAt: string
}

// ─── AI Processing Detail ────────────────────────────────────────────────────
export interface AIPProcessingDetail {
  step: string
  status: 'success' | 'warning' | 'error' | 'info'
  message: string
  timestamp: string
  duration?: number  // ms
}

// ─── Attached File (for AI agent processing) ─────────────────────────────────
export interface AttachedFile {
  id: string
  name: string
  size: number
  type: string
  category: 'justificatif' | 'complement' | 'photo' | 'autre'
  uploadedAt: string
  verified: boolean
}

export interface CitizenRequest {
  id: string
  reference: string
  serviceId: string
  serviceName: string
  category: string
  categoryId: string
  // Citoyen
  citizenName: string
  citizenFirstName: string
  citizenNIN: string
  citizenPhone: string
  citizenEmail: string
  citizenAddress: string
  // Demande
  motif: string
  documents: string[]
  uploadedDocuments: UploadedDocument[]  // Files uploaded by the citizen
  generatedDocument?: GeneratedDocument  // The official document generated by the agent
  satisfaction?: SatisfactionRating
  // Traitement
  status: RequestStatus
  assignedService: string
  assignedAgent: string
  processingNotes: ProcessingNote[]
  timeline: TimelineStep[]
  // Dates
  createdAt: string
  updatedAt: string
  completedAt?: string
  // Mairie
  mairie?: string  // Specific mairie name (e.g., "Mairie de Kaloum") for etat-civil/residence requests
  // Livraison
  deliveryMode: 'en_ligne' | 'guichet' | 'courrier'
  deliveryLocation?: string
  documentUrl?: string
  // IA
  aiProcessingStatus?: 'none' | 'ai_pending' | 'ai_processing' | 'ai_completed' | 'ai_failed' | 'ai_auto_validated' | 'ai_auto_rejected' | 'ai_assisted'
  aiConfidence?: number
  aiProcessingDate?: string
  aiProcessingDetails?: AIPProcessingDetail[]
  attachedFiles?: AttachedFile[]
}

export interface ProcessingNote {
  id: string
  author: string
  authorRole: string
  text: string
  date: string
  type: 'note' | 'decision' | 'info_complementaire' | 'notification'
}

export interface TimelineStep {
  label: string
  status: 'completed' | 'current' | 'pending'
  date?: string
  agent?: string
}

const SERVICE_ENTITY_MAP: Record<string, string> = {
  'etat-civil': 'Mairie / Commune',
  'justice': 'Ministère de la Justice',
  'identification': 'Agence Nationale d\'Identification (ANIP)',
  'urbanisme': 'Direction de l\'Urbanisme',
  'entreprise': 'APIP — Agence de Promotion des Investissements Privés',
  'education': 'Ministère de l\'Éducation Nationale',
  'sante': 'Ministère de la Santé',
  'residence': 'Mairie / Commune',
}

function generateReference(): string {
  return `GN-2026-${String(Math.floor(100000 + Math.random() * 900000))}`
}

function generateTimeline(category: string): TimelineStep[] {
  return [
    { label: 'Soumission de la demande', status: 'completed' },
    { label: 'Vérification des pièces justificatives', status: 'pending' },
    { label: 'Traitement par le service compétent', status: 'pending' },
    { label: 'Validation par le responsable', status: 'pending' },
    { label: 'Document prêt', status: 'pending' },
    { label: 'Livraison / Retrait', status: 'pending' },
  ]
}

// ─── DEMO SEED DATA ──────────────────────────────────────────────────────────
const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString()

// Small demo file data (1x1 transparent PNG base64)
const DEMO_PNG_DATA = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='
// Small demo PDF base64 (minimal PDF)
const DEMO_PDF_DATA = 'data:application/pdf;base64,JVBERi0xLjAKMSAwIG9iago8PAovVHlwZSAvQ2F0YWxvZwovUGFnZXMgMiAwIAo+PgplbmRvYmogMiAwIG9iago8PAovVHlwZSAvUGFnZXMKL0tpZHMgWzMgMCBdCi9Db3VudCAxCj4+CmVuZG9iaiAzIDAgb2JqCjw8Ci9UeXBlIC9QYWdlCi9QYXJlbnQgMiAwIAovTWVkaWFCb3ggWzAgMCAzMDAgMTQ0XQovQ29udGVudHMgNCAwIAo+PgplbmRvYmogNCAwIG9iago8PAovTGVuZ3RoIDQ0Cj4+CnN0cmVhbQpCVAovRiAxIDAKMjAgMTIwIFRkCihEZW1vIERvY3VtZW50KSBUagpFVEoKZW5kc3RyZWFtCmVuZG9iagp4cmVmCjAgNQowMDAwMDAwMDAwIDY1NTM1IAowMDAwMDAwMDE1IDAwMDAwIAowMDAwMDAwMDc0IDAwMDAwIAowMDAwMDAwMTM3IDAwMDAwIAowMDAwMDAwMjMxIDAwMDAwIAp0cmFpbGVyCjw8Ci9TaXplIDUKL1Jvb3QgMSAwIAo+PgpzdGFydHhyZWYKMTg1CiUlRU9G'

const DEMO_REQUESTS: CitizenRequest[] = [
  {
    id: 'demo-001',
    reference: 'GN-2026-100234',
    serviceId: 'ec-1',
    serviceName: "Extrait d'acte de naissance",
    category: 'État Civil',
    categoryId: 'etat-civil',
    citizenName: 'Diallo',
    citizenFirstName: 'Aminata',
    citizenNIN: 'NIN-2019-458723',
    citizenPhone: '+224 622 34 56 78',
    citizenEmail: 'citoyen@eadmin.gn',
    citizenAddress: 'Conakry, Commune de Kaloum',
    mairie: 'Mairie de Kaloum',
    motif: "Demande d'extrait d'acte de naissance pour dossier d'emploi",
    documents: ["Carte d'identité", 'Acte de naissance original ou numéro d\'acte'],
    uploadedDocuments: [
      {
        id: 'demo-doc-001',
        name: 'carte-identite-diallo.pdf',
        type: 'application/pdf',
        size: 245000,
        data: DEMO_PDF_DATA,
        uploadedAt: daysAgo(3),
        requiredDocName: "Carte d'identité",
        verified: true,
      },
    ],
    status: 'en_cours',
    assignedService: 'Mairie / Commune',
    assignedAgent: 'Mme. Fatoumata Bah',
    processingNotes: [
      { id: 'pn-001', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-100234. Service compétent: Mairie / Commune', date: daysAgo(3), type: 'notification' },
      { id: 'pn-002', author: 'Mme. Fatoumata Bah', authorRole: 'Agent', text: 'Demande prise en charge. Vérification des pièces en cours.', date: daysAgo(2), type: 'note' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: daysAgo(3) },
      { label: 'Vérification des pièces justificatives', status: 'current', date: daysAgo(2), agent: 'Mme. Fatoumata Bah' },
      { label: 'Traitement par le service compétent', status: 'pending' },
      { label: 'Validation par le responsable', status: 'pending' },
      { label: 'Document prêt', status: 'pending' },
      { label: 'Livraison / Retrait', status: 'pending' },
    ],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    deliveryMode: 'guichet',
    deliveryLocation: 'Mairie de Kaloum',
  },
  {
    id: 'demo-002',
    reference: 'GN-2026-100567',
    serviceId: 'id-1',
    serviceName: "Carte d'identité nationale biométrique",
    category: 'Identification',
    categoryId: 'identification',
    citizenName: 'Condé',
    citizenFirstName: 'Ibrahim',
    citizenNIN: 'NIN-2017-123456',
    citizenPhone: '+224 666 78 90 12',
    citizenEmail: 'ibrahin.conde@email.com',
    citizenAddress: 'Conakry, Commune de Matam',
    motif: "Renouvellement de carte d'identité biométrique arrivée à expiration",
    documents: ["Extrait d'acte de naissance", 'Certificat de nationalité', "4 photos d'identité", 'Certificat de résidence', 'Témoin avec CNI valide'],
    uploadedDocuments: [],
    status: 'validee',
    assignedService: 'Agence Nationale d\'Identification (ANIP)',
    assignedAgent: 'M. Mamadou Soumah',
    processingNotes: [
      { id: 'pn-003', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-100567. Service compétent: ANIP', date: daysAgo(7), type: 'notification' },
      { id: 'pn-004', author: 'M. Mamadou Soumah', authorRole: 'Agent', text: 'Pièces vérifiées et conformes. En cours de production.', date: daysAgo(5), type: 'note' },
      { id: 'pn-005', author: 'M. Mamadou Soumah', authorRole: 'Agent', text: 'Demande validée par le responsable. Production de la CNI lancée.', date: daysAgo(2), type: 'decision' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: daysAgo(7) },
      { label: 'Vérification des pièces justificatives', status: 'completed', date: daysAgo(5), agent: 'M. Mamadou Soumah' },
      { label: 'Traitement par le service compétent', status: 'completed', date: daysAgo(3), agent: 'M. Mamadou Soumah' },
      { label: 'Validation par le responsable', status: 'completed', date: daysAgo(2), agent: 'M. Mamadou Soumah' },
      { label: 'Document prêt', status: 'current' },
      { label: 'Livraison / Retrait', status: 'pending' },
    ],
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
    deliveryMode: 'guichet',
    deliveryLocation: 'Centre ANIP de Conakry',
  },
  {
    id: 'demo-003',
    reference: 'GN-2026-100890',
    serviceId: 'j-1',
    serviceName: 'Casier judiciaire',
    category: 'Justice & Légal',
    categoryId: 'justice',
    citizenName: 'Camara',
    citizenFirstName: 'Ousmane',
    citizenNIN: 'NIN-2020-789012',
    citizenPhone: '+224 655 12 34 56',
    citizenEmail: 'ousmane.camara@email.com',
    citizenAddress: 'Kindia, Préfecture de Kindia',
    motif: 'Casier judiciaire requis pour demande d\'emploi à la BCRG',
    documents: ["Carte d'identité nationale", "2 photos d'identité", 'Timbre fiscal'],
    uploadedDocuments: [],
    status: 'soumise',
    assignedService: 'Ministère de la Justice',
    assignedAgent: '',
    processingNotes: [
      { id: 'pn-006', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-100890. Service compétent: Ministère de la Justice', date: hoursAgo(4), type: 'notification' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: hoursAgo(4) },
      { label: 'Vérification des pièces justificatives', status: 'pending' },
      { label: 'Traitement par le service compétent', status: 'pending' },
      { label: 'Validation par le responsable', status: 'pending' },
      { label: 'Document prêt', status: 'pending' },
      { label: 'Livraison / Retrait', status: 'pending' },
    ],
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
    deliveryMode: 'en_ligne',
  },
  {
    id: 'demo-004',
    reference: 'GN-2026-101123',
    serviceId: 'e-1',
    serviceName: 'Enregistrement entreprise (APIP)',
    category: 'Entreprise & Commerce',
    categoryId: 'entreprise',
    citizenName: 'Touré',
    citizenFirstName: 'Mariama',
    citizenNIN: 'NIN-2018-345678',
    citizenPhone: '+224 628 45 67 89',
    citizenEmail: 'mariama.toure@entreprise-gn.com',
    citizenAddress: 'Conakry, Commune de Dixinn',
    motif: "Création d'une SARL dans le secteur du commerce général",
    documents: ["Statuts de l'entreprise", "Pièce d'identité du gérant", 'Casier judiciaire du gérant', 'Attestation de siège social', 'Capital social minimum'],
    uploadedDocuments: [],
    status: 'prete',
    assignedService: 'APIP — Agence de Promotion des Investissements Privés',
    assignedAgent: 'M. Alpha Diallo',
    processingNotes: [
      { id: 'pn-007', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-101123. Service compétent: APIP', date: daysAgo(10), type: 'notification' },
      { id: 'pn-008', author: 'M. Alpha Diallo', authorRole: 'Agent', text: 'Dossier complet, vérification en cours.', date: daysAgo(8), type: 'note' },
      { id: 'pn-009', author: 'M. Alpha Diallo', authorRole: 'Agent', text: 'Dossier approuvé. Enregistrement RCCM en cours.', date: daysAgo(5), type: 'decision' },
      { id: 'pn-010', author: 'M. Alpha Diallo', authorRole: 'Agent', text: 'Document prêt ! Veuillez le récupérer au guichet APIP.', date: daysAgo(1), type: 'notification' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: daysAgo(10) },
      { label: 'Vérification des pièces justificatives', status: 'completed', date: daysAgo(8), agent: 'M. Alpha Diallo' },
      { label: 'Traitement par le service compétent', status: 'completed', date: daysAgo(5), agent: 'M. Alpha Diallo' },
      { label: 'Validation par le responsable', status: 'completed', date: daysAgo(3), agent: 'M. Alpha Diallo' },
      { label: 'Document prêt', status: 'completed', date: daysAgo(1), agent: 'M. Alpha Diallo' },
      { label: 'Livraison / Retrait', status: 'current' },
    ],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    deliveryMode: 'guichet',
    deliveryLocation: 'Guichet APIP, Conakry',
  },
  {
    id: 'demo-005',
    reference: 'GN-2026-101456',
    serviceId: 'ec-4',
    serviceName: 'Certificat de nationalité',
    category: 'État Civil',
    categoryId: 'etat-civil',
    citizenName: 'Diallo',
    citizenFirstName: 'Aminata',
    citizenNIN: 'NIN-2019-458723',
    citizenPhone: '+224 622 34 56 78',
    citizenEmail: 'citoyen@eadmin.gn',
    citizenAddress: 'Kankan, Préfecture de Kankan',
    mairie: 'Mairie de Kankan',
    motif: 'Certificat de nationalité pour inscription sur les listes électorales',
    documents: ["Carte d'identité nationale", "Extrait d'acte de naissance", "2 photos d'identité", 'Certificat de résidence'],
    uploadedDocuments: [],
    status: 'pieces_complementaires',
    assignedService: 'Mairie / Commune',
    assignedAgent: 'Mme. Aissatou Sylla',
    processingNotes: [
      { id: 'pn-011', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-101456. Service compétent: Mairie / Commune', date: daysAgo(5), type: 'notification' },
      { id: 'pn-012', author: 'Mme. Aissatou Sylla', authorRole: 'Agent', text: 'Certificat de résidence manquant. Veuillez fournir un certificat de résidence en cours de validité (moins de 3 mois).', date: daysAgo(3), type: 'info_complementaire' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: daysAgo(5) },
      { label: 'Vérification des pièces justificatives', status: 'current', date: daysAgo(3), agent: 'Mme. Aissatou Sylla' },
      { label: 'Traitement par le service compétent', status: 'pending' },
      { label: 'Validation par le responsable', status: 'pending' },
      { label: 'Document prêt', status: 'pending' },
      { label: 'Livraison / Retrait', status: 'pending' },
    ],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
    deliveryMode: 'courrier',
  },
  {
    id: 'demo-006',
    reference: 'GN-2026-101789',
    serviceId: 'id-2',
    serviceName: 'Passeport biométrique',
    category: 'Identification',
    categoryId: 'identification',
    citizenName: 'Bah',
    citizenFirstName: 'Fatoumata',
    citizenNIN: 'NIN-2016-234567',
    citizenPhone: '+224 664 32 10 98',
    citizenEmail: 'fatoumata.bah@email.com',
    citizenAddress: 'Conakry, Commune de Ratoma',
    motif: 'Demande de passeport biométrique pour voyage professionnel en Europe',
    documents: ["Carte d'identité nationale", "Extrait d'acte de naissance", "4 photos d'identité récentes", 'Certificat de résidence', 'Ancien passeport (si renouvellement)'],
    uploadedDocuments: [
      {
        id: 'demo-doc-006a',
        name: 'cni-bah-fatoumata.pdf',
        type: 'application/pdf',
        size: 312000,
        data: DEMO_PDF_DATA,
        uploadedAt: daysAgo(15),
        requiredDocName: "Carte d'identité nationale",
        verified: true,
      },
      {
        id: 'demo-doc-006b',
        name: 'extrait-naissance-bah.png',
        type: 'image/png',
        size: 156000,
        data: DEMO_PNG_DATA,
        uploadedAt: daysAgo(15),
        requiredDocName: "Extrait d'acte de naissance",
        verified: true,
      },
      {
        id: 'demo-doc-006c',
        name: 'photos-identite-bah.png',
        type: 'image/png',
        size: 89000,
        data: DEMO_PNG_DATA,
        uploadedAt: daysAgo(15),
        requiredDocName: "4 photos d'identité récentes",
        verified: true,
      },
      {
        id: 'demo-doc-006d',
        name: 'certificat-residence-bah.pdf',
        type: 'application/pdf',
        size: 178000,
        data: DEMO_PDF_DATA,
        uploadedAt: daysAgo(15),
        requiredDocName: 'Certificat de résidence',
        verified: true,
      },
    ],
    generatedDocument: {
      id: 'gen-doc-006',
      title: 'Passeport biométrique — République de Guinée',
      htmlContent: `<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>Passeport biométrique — République de Guinée</title>
  <style>
    @page { size: A4; margin: 2cm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Times New Roman', Georgia, serif; color: #1a1a1a; line-height: 1.6; padding: 2cm; max-width: 21cm; margin: 0 auto; }
    .tricolor { display: flex; width: 100%; height: 6px; margin-bottom: 20px; }
    .tricolor-red { flex: 1; background-color: #CE1126; }
    .tricolor-yellow { flex: 1; background-color: #FCD116; }
    .tricolor-green { flex: 1; background-color: #009460; }
    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #0B2E58; padding-bottom: 20px; }
    .header h1 { font-size: 11pt; letter-spacing: 3px; text-transform: uppercase; color: #0B2E58; }
    .header .motto { font-size: 9pt; color: #666; letter-spacing: 1px; }
    .header .institution { font-size: 10pt; color: #0B2E58; font-weight: bold; margin-top: 8px; }
    .doc-title { text-align: center; margin: 30px 0 20px; }
    .doc-title h2 { font-size: 14pt; color: #0B2E58; text-transform: uppercase; letter-spacing: 1px; }
    .doc-title .ref { font-size: 11pt; color: #333; margin-top: 4px; }
    .info-box { border: 1px solid #0B2E58; padding: 16px; margin: 20px 0; border-radius: 4px; }
    .info-box h3 { font-size: 10pt; color: #0B2E58; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 10px; border-bottom: 1px solid #ccc; padding-bottom: 6px; }
    .info-row { display: flex; margin-bottom: 6px; font-size: 11pt; }
    .info-row .label { width: 180px; color: #666; font-style: italic; }
    .info-row .value { font-weight: 600; flex: 1; }
    .content { text-align: justify; margin: 20px 0; font-size: 12pt; }
    .content p { margin-bottom: 12px; text-indent: 1.5cm; }
    .signature { margin-top: 60px; text-align: right; }
    .signature .date { font-size: 10pt; color: #333; }
    .signature .signataire { font-size: 11pt; font-weight: bold; color: #0B2E58; margin-top: 8px; }
    .signature .line { width: 200px; border-bottom: 1px dashed #999; margin-top: 40px; margin-left: auto; }
    .signature .label-sign { font-size: 9pt; color: #666; margin-top: 4px; }
    .footer { margin-top: 40px; border-top: 1px solid #ddd; padding-top: 10px; font-size: 8pt; color: #999; text-align: center; }
    .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 48pt; color: rgba(11, 46, 88, 0.04); letter-spacing: 5px; pointer-events: none; white-space: nowrap; }
    @media print { body { padding: 0; } .watermark { display: block; } }
  </style>
</head>
<body>
  <div class="watermark">eAdmin Guinée — République de Guinée</div>
  <div class="tricolor">
    <div class="tricolor-red"></div>
    <div class="tricolor-yellow"></div>
    <div class="tricolor-green"></div>
  </div>
  <div class="header">
    <h1>République de Guinée</h1>
    <div class="motto">Travail — Justice — Solidarité</div>
    <div class="institution">Agence Nationale d'Identification (ANIP)</div>
  </div>
  <div class="doc-title">
    <h2>Passeport biométrique</h2>
    <div class="ref">Référence : GN-2026-101789</div>
  </div>
  <div class="info-box">
    <h3>Informations du titulaire</h3>
    <div class="info-row"><span class="label">Nom complet :</span><span class="value">Fatoumata Bah</span></div>
    <div class="info-row"><span class="label">NIN :</span><span class="value">NIN-2016-234567</span></div>
    <div class="info-row"><span class="label">Téléphone :</span><span class="value">+224 664 32 10 98</span></div>
    <div class="info-row"><span class="label">Adresse :</span><span class="value">Conakry, Commune de Ratoma</span></div>
    <div class="info-row"><span class="label">Type de document :</span><span class="value">Passeport biométrique international</span></div>
  </div>
  <div class="content">
    <p>Par la présente, il est certifié que le passeport biométrique sus-référencé a été établi conformément aux dispositions légales et réglementaires en vigueur en République de Guinée, et en conformité avec les standards de l'OACI.</p>
    <p>Le présent document est délivré pour faire valoir ce que de droit. Toute falsification ou utilisation frauduleuse expose son auteur aux poursuites prévues par la loi guinéenne.</p>
  </div>
  <div class="signature">
    <div class="date">Fait à Conakry, le ${new Date(daysAgo(8)).toLocaleDateString('fr-FR')}</div>
    <div class="signataire">Agence Nationale d'Identification (ANIP)</div>
    <div class="line"></div>
    <div class="label-sign">Signature & Cachet officiel</div>
  </div>
  <div class="footer">
    Ce document est généré par le système eAdmin Guinée de la République de Guinée — GN-2026-101789 — ${new Date().toLocaleDateString('fr-FR')}
  </div>
</body>
</html>`,
      generatedAt: daysAgo(8),
      generatedBy: 'M. Ibrahima Keita',
      fileName: 'GN-2026-101789-passeport-biometrique.html',
    },
    status: 'livree',
    assignedService: 'Agence Nationale d\'Identification (ANIP)',
    assignedAgent: 'M. Ibrahima Keita',
    processingNotes: [
      { id: 'pn-013', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-101789. Service compétent: ANIP', date: daysAgo(15), type: 'notification' },
      { id: 'pn-014', author: 'M. Ibrahima Keita', authorRole: 'Agent', text: 'Dossier complet et conforme.', date: daysAgo(13), type: 'note' },
      { id: 'pn-015', author: 'M. Ibrahima Keita', authorRole: 'Agent', text: 'Passeport produit et prêt pour retrait.', date: daysAgo(8), type: 'decision' },
      { id: 'pn-016', author: 'M. Ibrahima Keita', authorRole: 'Agent', text: 'Passeport biométrique remis au citoyen au guichet ANIP de Conakry.', date: daysAgo(5), type: 'notification' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: daysAgo(15) },
      { label: 'Vérification des pièces justificatives', status: 'completed', date: daysAgo(13), agent: 'M. Ibrahima Keita' },
      { label: 'Traitement par le service compétent', status: 'completed', date: daysAgo(10), agent: 'M. Ibrahima Keita' },
      { label: 'Validation par le responsable', status: 'completed', date: daysAgo(9), agent: 'M. Ibrahima Keita' },
      { label: 'Document prêt', status: 'completed', date: daysAgo(8), agent: 'M. Ibrahima Keita' },
      { label: 'Livraison / Retrait', status: 'completed', date: daysAgo(5), agent: 'M. Ibrahima Keita' },
    ],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(5),
    completedAt: daysAgo(5),
    deliveryMode: 'guichet',
    deliveryLocation: 'Guichet ANIP, Conakry',
  },
  {
    id: 'demo-007',
    reference: 'GN-2026-102012',
    serviceId: 'ed-1',
    serviceName: 'Attestation de scolarité',
    category: 'Éducation',
    categoryId: 'education',
    citizenName: 'Keita',
    citizenFirstName: 'Mamadou',
    citizenNIN: 'NIN-2021-890123',
    citizenPhone: '+224 677 56 78 90',
    citizenEmail: '',
    citizenAddress: 'Labé, Préfecture de Labé',
    motif: "Attestation de scolarité pour bourse d'étude",
    documents: ["Carte d'identité", "Certificat d'inscription", 'Dernier bulletin scolaire'],
    uploadedDocuments: [],
    status: 'rejetee',
    assignedService: 'Ministère de l\'Éducation Nationale',
    assignedAgent: 'M. Cheick Sylla',
    processingNotes: [
      { id: 'pn-017', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-102012. Service compétent: Ministère de l\'Éducation Nationale', date: daysAgo(6), type: 'notification' },
      { id: 'pn-018', author: 'M. Cheick Sylla', authorRole: 'Agent', text: 'Dernier bulletin scolaire non fourni. Demande incomplète, impossibilité de traiter le dossier.', date: daysAgo(4), type: 'decision' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: daysAgo(6) },
      { label: 'Vérification des pièces justificatives', status: 'completed', date: daysAgo(4), agent: 'M. Cheick Sylla' },
      { label: 'Traitement par le service compétent', status: 'pending' },
      { label: 'Validation par le responsable', status: 'pending' },
      { label: 'Document prêt', status: 'pending' },
      { label: 'Livraison / Retrait', status: 'pending' },
    ],
    createdAt: daysAgo(6),
    updatedAt: daysAgo(4),
    deliveryMode: 'guichet',
  },
  {
    id: 'demo-008',
    reference: 'GN-2026-102345',
    serviceId: 's-1',
    serviceName: 'Certificat de vaccination',
    category: 'Santé',
    categoryId: 'sante',
    citizenName: 'Doubé',
    citizenFirstName: 'Aïssatou',
    citizenNIN: 'NIN-2022-456789',
    citizenPhone: '+224 620 11 22 33',
    citizenEmail: 'aissatou.doube@email.com',
    citizenAddress: 'N\'Zérékoré, Préfecture de N\'Zérékoré',
    motif: 'Certificat de vaccination international pour voyage',
    documents: ["Carte d'identité", 'Ancien carnet de vaccination (si disponible)'],
    uploadedDocuments: [],
    status: 'soumise',
    assignedService: 'Ministère de la Santé',
    assignedAgent: '',
    processingNotes: [
      { id: 'pn-019', author: 'Système', authorRole: 'Automate', text: 'Demande soumise avec succès. Référence: GN-2026-102345. Service compétent: Ministère de la Santé', date: hoursAgo(2), type: 'notification' },
    ],
    timeline: [
      { label: 'Soumission de la demande', status: 'completed', date: hoursAgo(2) },
      { label: 'Vérification des pièces justificatives', status: 'pending' },
      { label: 'Traitement par le service compétent', status: 'pending' },
      { label: 'Validation par le responsable', status: 'pending' },
      { label: 'Document prêt', status: 'pending' },
      { label: 'Livraison / Retrait', status: 'pending' },
    ],
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    deliveryMode: 'en_ligne',
  },
]

interface CitizenRequestsState {
  requests: CitizenRequest[]
  addRequest: (req: Omit<CitizenRequest, 'id' | 'reference' | 'status' | 'timeline' | 'processingNotes' | 'updatedAt' | 'assignedService' | 'assignedAgent'>) => CitizenRequest
  updateRequestStatus: (id: string, status: RequestStatus, note?: string) => void
  addProcessingNote: (id: string, note: Omit<ProcessingNote, 'id' | 'date'>) => void
  advanceTimeline: (id: string) => void
  assignRequest: (id: string, agent: string) => void
  completeRequest: (id: string, deliveryMode: CitizenRequest['deliveryMode'], deliveryLocation?: string) => void
  getRequestById: (id: string) => CitizenRequest | undefined
  getRequestByReference: (ref: string) => CitizenRequest | undefined
  getRequestsByCategory: (categoryId: string) => CitizenRequest[]
  getRequestsByStatus: (status: RequestStatus) => CitizenRequest[]
  addUploadedDocument: (id: string, doc: UploadedDocument) => void
  removeUploadedDocument: (requestId: string, docId: string) => void
  verifyDocument: (requestId: string, docId: string) => void
  setGeneratedDocument: (id: string, doc: GeneratedDocument) => void
  rateRequest: (id: string, rating: SatisfactionRating) => void
  resetToDemoData: () => void
  // AI Agent methods
  aiAutoProcess: (id: string) => void
  aiAutoProcessAll: () => void
  updateRequestAIFields: (id: string, fields: Partial<Pick<CitizenRequest, 'aiProcessingStatus' | 'aiConfidence' | 'aiProcessingDate' | 'aiProcessingDetails' | 'status' | 'assignedAgent' | 'processingNotes' | 'timeline' | 'updatedAt'>>) => void
}

export const useCitizenRequestsStore = create<CitizenRequestsState>()(
  persist(
    (set, get) => ({
      requests: DEMO_REQUESTS,

      addRequest: (req) => {
        const id = `req-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
        const reference = generateReference()
        const nowIso = new Date().toISOString()
        const assignedService = SERVICE_ENTITY_MAP[req.categoryId] || 'Administration Générale'

        // Auto-set mairie for etat-civil and residence requests
        let mairie = req.mairie
        if ((req.categoryId === 'etat-civil' || req.categoryId === 'residence') && !mairie) {
          const communeMatch = req.citizenAddress.match(/Commune de\s+(.+)/i)
          if (communeMatch) {
            mairie = `Mairie de ${communeMatch[1].trim()}`
          } else {
            mairie = 'Mairie de Kaloum'
          }
        }

        const newRequest: CitizenRequest = {
          ...req,
          mairie,
          id,
          reference,
          status: 'soumise',
          assignedService,
          assignedAgent: '',
          timeline: generateTimeline(req.categoryId),
          processingNotes: [{
            id: `note-${Date.now()}`,
            author: 'Système',
            authorRole: 'Automate',
            text: `Demande soumise avec succès. Référence: ${reference}. Service compétent: ${assignedService}`,
            date: nowIso,
            type: 'notification',
          }],
          updatedAt: nowIso,
        }

        set((state) => ({ requests: [newRequest, ...state.requests] }))
        return newRequest
      },

      updateRequestStatus: (id, status, note) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? {
                  ...r,
                  status,
                  updatedAt: new Date().toISOString(),
                  completedAt: status === 'livree' ? new Date().toISOString() : r.completedAt,
                  processingNotes: note
                    ? [...r.processingNotes, {
                        id: `note-${Date.now()}`,
                        author: 'Agent traitant',
                        authorRole: 'Agent',
                        text: note,
                        date: new Date().toISOString(),
                        type: 'decision' as const,
                      }]
                    : r.processingNotes,
                }
              : r
          ),
        }))
      },

      addProcessingNote: (id, note) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? {
                  ...r,
                  updatedAt: new Date().toISOString(),
                  processingNotes: [...r.processingNotes, {
                    ...note,
                    id: `note-${Date.now()}`,
                    date: new Date().toISOString(),
                  }],
                }
              : r
          ),
        }))
      },

      advanceTimeline: (id) => {
        set((state) => ({
          requests: state.requests.map(r => {
            if (r.id !== id) return r
            const currentIdx = r.timeline.findIndex(s => s.status === 'current')
            const completedIdx = r.timeline.findIndex(s => s.status === 'completed')
            // If no current, first pending becomes current
            if (currentIdx === -1) {
              const firstPending = r.timeline.findIndex(s => s.status === 'pending')
              if (firstPending === -1) return r
              const newTimeline = r.timeline.map((step, i) =>
                i === firstPending ? { ...step, status: 'current' as const, date: new Date().toISOString() } : step
              )
              return { ...r, timeline: newTimeline, updatedAt: new Date().toISOString() }
            }
            // Complete current, advance next
            const newTimeline = r.timeline.map((step, i) => {
              if (i === currentIdx) return { ...step, status: 'completed' as const, date: new Date().toISOString() }
              if (i === currentIdx + 1 && step.status === 'pending') return { ...step, status: 'current' as const }
              return step
            })
            return { ...r, timeline: newTimeline, updatedAt: new Date().toISOString() }
          }),
        }))
      },

      assignRequest: (id, agent) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? { ...r, assignedAgent: agent, updatedAt: new Date().toISOString() }
              : r
          ),
        }))
      },

      completeRequest: (id, deliveryMode, deliveryLocation) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? {
                  ...r,
                  status: 'livree' as const,
                  deliveryMode,
                  deliveryLocation,
                  completedAt: new Date().toISOString(),
                  updatedAt: new Date().toISOString(),
                  timeline: r.timeline.map(step => ({
                    ...step,
                    status: 'completed' as const,
                    date: step.date || new Date().toISOString(),
                  })),
                }
              : r
          ),
        }))
      },

      addUploadedDocument: (id, doc) => {
        // localStorage protection: trim base64 data if total stored size would exceed ~4MB
        const MAX_LOCALSTORAGE_PER_DOC = 2 * 1024 * 1024 // 2MB per document
        const safeDoc = doc.data.length > MAX_LOCALSTORAGE_PER_DOC
          ? { ...doc, data: doc.data.slice(0, MAX_LOCALSTORAGE_PER_DOC), _truncated: true as any }
          : doc

        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? {
                  ...r,
                  uploadedDocuments: [...r.uploadedDocuments, safeDoc],
                  updatedAt: new Date().toISOString(),
                }
              : r
          ),
        }))
      },

      removeUploadedDocument: (requestId, docId) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === requestId
              ? {
                  ...r,
                  uploadedDocuments: r.uploadedDocuments.filter(d => d.id !== docId),
                  updatedAt: new Date().toISOString(),
                }
              : r
          ),
        }))
      },

      verifyDocument: (requestId, docId) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === requestId
              ? {
                  ...r,
                  uploadedDocuments: r.uploadedDocuments.map(d =>
                    d.id === docId ? { ...d, verified: true } : d
                  ),
                  updatedAt: new Date().toISOString(),
                }
              : r
          ),
        }))
      },

      setGeneratedDocument: (id, doc) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? {
                  ...r,
                  generatedDocument: doc,
                  updatedAt: new Date().toISOString(),
                }
              : r
          ),
        }))
      },

      rateRequest: (id, rating) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? { ...r, satisfaction: rating, updatedAt: new Date().toISOString() }
              : r
          ),
        }))
      },

      resetToDemoData: () => {
        set({ requests: DEMO_REQUESTS })
      },

      // AI Agent: Auto-process a single request with simulated AI decision
      aiAutoProcess: (id) => {
        const req = get().requests.find(r => r.id === id)
        if (!req) return

        // Simple simulated AI logic: if documents are complete, validate; otherwise request more info
        const uploadedCount = req.uploadedDocuments?.length ?? 0
        const requiredCount = req.documents?.length ?? 0
        const verifiedCount = (req.uploadedDocuments ?? []).filter(d => d.verified).length

        let aiStatus: CitizenRequest['aiProcessingStatus']
        let newStatus: RequestStatus = req.status
        const now = new Date().toISOString()
        const confidence = Math.min(95, 50 + (verifiedCount * 15) + (uploadedCount >= requiredCount ? 20 : 0))

        if (uploadedCount >= requiredCount && verifiedCount >= requiredCount) {
          // All docs uploaded and verified -> auto validate
          aiStatus = 'ai_auto_validated'
          newStatus = 'validee'
        } else if (uploadedCount >= requiredCount && verifiedCount < requiredCount) {
          // Docs uploaded but not all verified -> assisted
          aiStatus = 'ai_assisted'
        } else if (uploadedCount === 0) {
          // No docs -> auto reject
          aiStatus = 'ai_auto_rejected'
          newStatus = 'rejetee'
        } else {
          // Some docs -> assisted
          aiStatus = 'ai_assisted'
        }

        const details: AIPProcessingDetail[] = [
          { step: 'Vérification IA', status: 'success', message: `Analyse des documents: ${uploadedCount}/${requiredCount} chargés, ${verifiedCount} vérifiés`, timestamp: now, duration: 150 },
          { step: 'Décision IA', status: aiStatus === 'ai_auto_validated' ? 'success' : aiStatus === 'ai_auto_rejected' ? 'error' : 'warning', message: `Confiance: ${confidence}%. ${aiStatus === 'ai_auto_validated' ? 'Validation automatique' : aiStatus === 'ai_auto_rejected' ? 'Rejet: documents manquants' : 'Escalade: vérification humaine requise'}`, timestamp: now, duration: 200 },
        ]

        const aiNote: ProcessingNote = {
          id: `note-ai-${Date.now()}`,
          author: 'Agent IA',
          authorRole: 'IA',
          text: `Traitement IA automatique: Confiance ${confidence}%. ${aiStatus === 'ai_auto_validated' ? 'Demande validée automatiquement.' : aiStatus === 'ai_auto_rejected' ? 'Rejetée: pièces justificatives manquantes.' : 'Escalade vers agent humain pour vérification.'}`,
          date: now,
          type: 'decision',
        }

        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? {
                  ...r,
                  status: newStatus,
                  aiProcessingStatus: aiStatus,
                  aiConfidence: confidence,
                  aiProcessingDate: now,
                  aiProcessingDetails: details,
                  assignedAgent: r.assignedAgent || 'Agent IA',
                  processingNotes: [...r.processingNotes, aiNote],
                  updatedAt: now,
                }
              : r
          ),
        }))
      },

      // AI Agent: Auto-process all pending requests
      aiAutoProcessAll: () => {
        const pendingRequests = get().requests.filter(
          r => r.status === 'soumise' && (!r.aiProcessingStatus || r.aiProcessingStatus === 'none' || r.aiProcessingStatus === 'ai_pending')
        )
        pendingRequests.forEach(r => get().aiAutoProcess(r.id))
      },

      // Update AI fields on a request (used by ai-agent-store for real AI processing)
      updateRequestAIFields: (id, fields) => {
        set((state) => ({
          requests: state.requests.map(r =>
            r.id === id
              ? { ...r, ...fields, updatedAt: fields.updatedAt || new Date().toISOString() }
              : r
          ),
        }))
      },

      getRequestById: (id) => get().requests.find(r => r.id === id),
      getRequestByReference: (ref) => get().requests.find(r => r.reference === ref || r.reference.includes(ref)),
      getRequestsByCategory: (categoryId) => get().requests.filter(r => r.categoryId === categoryId),
      getRequestsByStatus: (status) => get().requests.filter(r => r.status === status),
    }),
    {
      name: 'citizen-requests-storage',
      version: 7,
      migrate: (persistedState: any, version: number) => {
        if (version < 7) {
          return { requests: DEMO_REQUESTS }
        }
        return persistedState
      },
    }
  )
)
