apiVersion: v1
kind: ConfigMap
metadata:
  name: eadmin-config
  namespace: eadmin
data:
  ENVIRONMENT: "production"
  APP_NAME: "eAdministration Suite Guinea"
  MFA_ISSUER: "eAdmin Guinée"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET_NAME: "eadmin-documents"
  MINIO_SECURE: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eadmin-frontend-config
  namespace: eadmin
data:
  NEXT_PUBLIC_API_URL: "https://api.eadmin.gouv.gn"
  NEXT_PUBLIC_APP_NAME: "eAdministration Suite Guinea"
