param(
    [ValidateSet("up", "down", "reset", "status", "logs")]
    [string]$Action = "up",
    [switch]$Observability
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $RepoRoot ".env.local"
$ComposeFile = Join-Path $RepoRoot "docker-compose.local.yml"

Set-Location $RepoRoot

function New-HexSecret {
    param([int]$Bytes = 32)
    $buffer = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($buffer)
    }
    finally {
        $rng.Dispose()
    }
    return ([System.BitConverter]::ToString($buffer)).Replace("-", "").ToLowerInvariant()
}

function Read-DotEnv {
    $values = @{}
    if (-not (Test-Path $EnvFile)) {
        return $values
    }

    foreach ($line in Get-Content $EnvFile) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#") -or -not $trimmed.Contains("=")) {
            continue
        }
        $parts = $trimmed.Split("=", 2)
        $values[$parts[0].Trim()] = $parts[1]
    }
    return $values
}

function Ensure-LocalEnv {
    $existing = Read-DotEnv
    $defaults = [ordered]@{
        POSTGRES_PASSWORD = New-HexSecret 24
        REDIS_PASSWORD = New-HexSecret 24
        MINIO_ROOT_USER = "eadmin"
        MINIO_ROOT_PASSWORD = New-HexSecret 24
        SECRET_KEY = New-HexSecret 48
        ENCRYPTION_KEY = New-HexSecret 32
        NEXT_PUBLIC_ENCRYPTION_KEY = New-HexSecret 32
        GRAFANA_ADMIN_USER = "admin"
        GRAFANA_ADMIN_PASSWORD = "Grafana!2026Aa-$(New-HexSecret 12)"
        LOCAL_TEST_PASSWORD = "Local!2026Aa-$(New-HexSecret 12)"
        LOCAL_TEST_DOMAIN = "eadmin.test"
        LOCAL_SUPERADMIN_EMAIL = "superadmin@eadmin.test"
        LOCAL_FRONTEND_PORT = "3000"
        LOCAL_BACKEND_PORT = "8000"
        LOCAL_POSTGRES_PORT = "5433"
        LOCAL_REDIS_PORT = "6380"
        LOCAL_MINIO_API_PORT = "9000"
        LOCAL_MINIO_CONSOLE_PORT = "9001"
        LOCAL_MAILPIT_SMTP_PORT = "1025"
        LOCAL_MAILPIT_UI_PORT = "8025"
        LOCAL_PROMETHEUS_PORT = "9090"
        LOCAL_GRAFANA_PORT = "3001"
    }

    $newLines = New-Object System.Collections.Generic.List[string]
    foreach ($entry in $defaults.GetEnumerator()) {
        if (-not $existing.ContainsKey($entry.Key) -or [string]::IsNullOrWhiteSpace($existing[$entry.Key])) {
            $newLines.Add("$($entry.Key)=$($entry.Value)")
        }
    }

    if (-not (Test-Path $EnvFile)) {
        $header = @(
            "# eAdmin local-only environment generated by scripts/local.ps1",
            "# This file is ignored by Git. Never reuse these secrets in staging/production.",
            ""
        ) -join [Environment]::NewLine
        $encoding = New-Object System.Text.UTF8Encoding($false)
        [System.IO.File]::WriteAllText($EnvFile, $header + [Environment]::NewLine, $encoding)
    }

    if ($newLines.Count -gt 0) {
        $encoding = New-Object System.Text.UTF8Encoding($false)
        $payload = ($newLines -join [Environment]::NewLine) + [Environment]::NewLine
        [System.IO.File]::AppendAllText($EnvFile, $payload, $encoding)
        Write-Host "Configuration locale mise à jour: .env.local" -ForegroundColor Green
    }
}

function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker n'est pas installé ou n'est pas dans le PATH. Installez/démarrez Docker Desktop."
    }

    & docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose v2 n'est pas disponible. Mettez Docker Desktop à jour."
    }

    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Desktop est installé mais le moteur Docker n'est pas démarré."
    }
}

function Invoke-LocalCompose {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$ComposeArgs)

    $args = @("compose", "--env-file", $EnvFile, "-f", $ComposeFile)
    if ($Observability) {
        $args += @("--profile", "observability")
    }
    $args += $ComposeArgs

    & docker @args
    if ($LASTEXITCODE -ne 0) {
        throw "La commande Docker Compose a échoué (code $LASTEXITCODE)."
    }
}

function Wait-Http {
    param(
        [string]$Url,
        [string]$Label,
        [int]$TimeoutSeconds = 180
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        try {
            $response = Invoke-WebRequest -UseBasicParsing -Uri $Url -TimeoutSec 5
            if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500) {
                Write-Host "$Label prêt: $Url" -ForegroundColor Green
                return
            }
        }
        catch {
            Start-Sleep -Seconds 2
            continue
        }
        Start-Sleep -Seconds 2
    }

    Write-Host "Logs backend récents:" -ForegroundColor Yellow
    try { Invoke-LocalCompose logs --tail 120 backend } catch { }
    throw "$Label n'a pas répondu dans le délai prévu: $Url"
}

function Show-LocalAccess {
    $envMap = Read-DotEnv
    $frontendPort = if ($envMap["LOCAL_FRONTEND_PORT"]) { $envMap["LOCAL_FRONTEND_PORT"] } else { "3000" }
    $backendPort = if ($envMap["LOCAL_BACKEND_PORT"]) { $envMap["LOCAL_BACKEND_PORT"] } else { "8000" }
    $mailpitPort = if ($envMap["LOCAL_MAILPIT_UI_PORT"]) { $envMap["LOCAL_MAILPIT_UI_PORT"] } else { "8025" }
    $minioPort = if ($envMap["LOCAL_MINIO_CONSOLE_PORT"]) { $envMap["LOCAL_MINIO_CONSOLE_PORT"] } else { "9001" }
    $domain = if ($envMap["LOCAL_TEST_DOMAIN"]) { $envMap["LOCAL_TEST_DOMAIN"] } else { "eadmin.test" }
    $superadmin = if ($envMap["LOCAL_SUPERADMIN_EMAIL"]) { $envMap["LOCAL_SUPERADMIN_EMAIL"] } else { "superadmin@eadmin.test" }
    $password = $envMap["LOCAL_TEST_PASSWORD"]

    Write-Host ""
    Write-Host "=== eAdmin Guinée local ===" -ForegroundColor Cyan
    Write-Host "Frontend : http://localhost:$frontendPort"
    Write-Host "Backend  : http://localhost:$backendPort"
    Write-Host "API docs : http://localhost:$backendPort/docs"
    Write-Host "Mailpit   : http://localhost:$mailpitPort"
    Write-Host "MinIO     : http://localhost:$minioPort"
    if ($Observability) {
        Write-Host "Prometheus: http://localhost:$($envMap['LOCAL_PROMETHEUS_PORT'])"
        Write-Host "Grafana   : http://localhost:$($envMap['LOCAL_GRAFANA_PORT'])"
    }

    Write-Host ""
    Write-Host "Comptes de test (même mot de passe local):" -ForegroundColor Cyan
    Write-Host "  SUPER_ADMIN  $superadmin"
    foreach ($slug in @("citoyen", "agent", "mairie", "agence", "admin", "chef-service", "directeur", "ministre")) {
        Write-Host ("  {0,-12} {1}@{2}" -f $slug.ToUpperInvariant(), $slug, $domain)
    }
    Write-Host "  Mot de passe : $password" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Ces identifiants sont uniquement locaux et sont stockés dans .env.local (ignoré par Git)." -ForegroundColor DarkGray
}

Assert-Docker
Ensure-LocalEnv

switch ($Action) {
    "up" {
        Write-Host "Construction et démarrage de la stack locale..." -ForegroundColor Cyan
        Invoke-LocalCompose up -d --build --remove-orphans
        $envMap = Read-DotEnv
        Wait-Http -Url "http://localhost:$($envMap['LOCAL_BACKEND_PORT'])/health" -Label "Backend"
        Wait-Http -Url "http://localhost:$($envMap['LOCAL_FRONTEND_PORT'])" -Label "Frontend"
        Show-LocalAccess
    }
    "down" {
        Invoke-LocalCompose down --remove-orphans
        Write-Host "Stack locale arrêtée. Les données sont conservées." -ForegroundColor Green
    }
    "reset" {
        Write-Host "Suppression des conteneurs et volumes LOCAUX eAdmin..." -ForegroundColor Yellow
        Invoke-LocalCompose down -v --remove-orphans
        Invoke-LocalCompose up -d --build --remove-orphans
        $envMap = Read-DotEnv
        Wait-Http -Url "http://localhost:$($envMap['LOCAL_BACKEND_PORT'])/health" -Label "Backend"
        Wait-Http -Url "http://localhost:$($envMap['LOCAL_FRONTEND_PORT'])" -Label "Frontend"
        Show-LocalAccess
    }
    "status" {
        Invoke-LocalCompose ps
        Show-LocalAccess
    }
    "logs" {
        Invoke-LocalCompose logs -f --tail 200
    }
}
